spring:
  application:
    name: consumer
  main:
    web-application-type: none
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    listener:
      simple:
        acknowledge-mode: manual     # Auto (fragile) or manual (dependable) depending on your logic
        concurrency: 2               # Number of consumer threads
        max-concurrency: 5
        retry:
          enabled: false             # Disable Spring's native retry when consumer fails to process message

consumer:
  queue: popov-rnd.queue             # Must match the queue declared by producer

logging:
  level:
    com.popovrnd.consumer: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework: WARN

